[package]
name = "cgt_mediapipe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgt_math = { git = "https://github.com/cgtinker/cgt_math", branch = "main" }
