from typing import List


def pose(data: List[List[float]]) -> List[List[float]]: ...
def hand(data: List[List[float]]) -> List[List[float]]: ...
def hands(data: List[List[List[float]]]) -> List[List[List[float]]]: ...
def face(data: List[List[float]]) -> List[List[float]]: ...
def holistic(data: List[List[List[float]]]) -> List[List[List[float]]]: ...
